routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/GuiaTracking.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class GuiaTracking extends Model
{
    use HasFactory;

    protected $fillable = [
        'idUsuario',
        'idGuia',
        'estado',
        'descripcion',
    ];

    public function getCreatedAtAttribute($value)
    {
        return $value ? Carbon::parse($value)->format('d-m-Y H:i:s') : null ;
    }
}

resources/views/pdfs/etiqueta.blade.php
<table style="width: 100%">
    <tr style="width: 100%">
        <td style="width: 20">
            <h3 class="text-uppercase">{{ $empresa->nombre }}</h3>
        </td>
        <td style="width: 80">
            <didv class="text-right">
                <h1>Guia: {{ $guia->oficina->codigo }}-{{ $guia->id }}</h1>
            </didv>
        </td>
    </tr>
</table>
<div class="contenido">
    <table style="width: 100%">
        <tr style="width: 100%" style="background-color: gray; color:white;">
            <td style="width: 50; text-align: center; font-weight: 900">ENVIADO POR:</td>
            <td style="width: 50; text-align: center; font-weight: 900">RECIBE:</td>
        </tr>
        <tr>
            <td style="width: 50; text-align: center; text-transform: uppercase">{{ $guia->cliente->documento }} - {{ $guia->cliente->nombres }} {{ $guia->cliente->apellidos }}</td>
            <td style="width: 50; text-align: center; text-transform: uppercase">{{ $guia->destinatario->documento }} - {{ $guia->destinatario->nombres }} {{ $guia->destinatario->apellidos }}</td>
        </tr>
    </table>

    <table style="width: 100%; margin-top: 2rem">
        <tr style="width: 100%" style="background-color: gray; color:white;">
            <td style="width: 30; text-align: center; font-weight: 900">PESO:</td>
            <td style="width: 30; text-align: center; font-weight: 900">PESO VOLUMETRICO:</td>
            <td style="width: 40; text-align: center; font-weight: 900">MEDIDAS:</td>
        </tr>
        <tr>
            <td style="width: 50; text-align: center;">{{ $guia->peso }} KG</td>
            <td style="width: 50; text-align: center;">{{ $guia->peso_volumetrico }}</td>
            <td style="width: 50; text-align: center;">{{ $guia->alto }} * {{ $guia->ancho }} * {{ $guia->largo }}</td>
        </tr>
    </table>

    <table style="width: 100%; margin-top: 2rem">
        <tr style="width: 100%" style="background-color: gray; color:white;">
            <td style="width: 30; text-align: center; font-weight: 900">Courier Destino:</td>
            <td style="width: 70; text-align: center; font-weight: 900">Oficina Destino:</td>
        </tr>
        <tr>
            <td style="width: 50; text-align: center; text-transform: uppercase">
            @if($guia->entregaPP != 1)
            ZOOM - {{ $guia->oficinaCourier->codigo }}
            @else
            ENTREGA PUERTA A PUERTA
            @endif
            </td>
                <td style="width: 50; text-align: center; text-transform: uppercase; text-align: justify;">
                    @if($guia->entregaPP != 1)
                 ({{ $guia->oficinaCourier->pais }} - {{ $guia->oficinaCourier->estado }} - {{ $guia->oficinaCourier->ciudad }})
                {{ $guia->oficinaCourier->direccion }}
                @else
                {{ $guia->destinatario->direccion }}
                @endif
            </td>
        </tr>
    </table>


    <footer>
        URL DE VERIFICACION: <a href="https://www.suramericacargo.com/tracking/{{ $guia->id }}">https://www.suramericacargo.com/tracking/{{ $guia->id }}</a>
        <br>
        Telefonos Empresa: {{ $empresa->telefono }} / Oficina: {{ $guia->oficina->telefono }}
    </footer>


</div>
<style>
    html {
    	margin: 1rem 3rem;
    }

    .contenido{
        width: 100%;
        height: 80%;
        text-align: center;
    }

    .text-right{
        width: 100%;
        text-align: right;
    }

    footer {
        position: fixed;
        bottom: 60px;
        left: 0px;
        right: 0px;
        height: 50px;
        text-align: left;
        line-height: 35px;
    }

    .text-uppercase{
        text-transform: uppercase
    }
</style>

resources/views/pdfs/manifiesto.blade.php
<style>
    @page {
        margin: 0cm 0.3cm 1cm 0.3cm;
        font-size: 8
    }

    body {
        margin-top: 2cm;
        margin-left: 0cm;
        margin-right: 0cm;
        margin-bottom: 1cm;
    }

    header {
        position: fixed;
        top: 0cm;
        left: 0cm;
        right: 0cm;
        height: 2cm;
        color: black;
        text-align: center;
        line-height: 1.5cm;
    }

    table {
        width: 100%
    }

    thead {
        background-color: gray;
        color: black;
    }

    thead>tr {
        background-color: gray;
        color: black;
    }

    thead>tr>td {
        background-color: gray;
        color: black;
    }
</style>

<body>
    <header>
        <table style="width: 100%">
            <tr style="width: 100%">
                <td style="width: 90%; font-size: 8">Manifiesto {{ '#' . $manifiesto->id }}</td>
                <td style="width: 20%; text-align:left!important; font-size: 8">{{ date('d/m/Y H:i:s A') }}</td>
            </tr>
        </table>
    </header>

    <table style="width: 100%">
        <thead>
            <tr>
                <td>Guia</td>
                <td>Courier</td>
                <td>Destino</td>
                <td>Remintente</td>
                <td>Destinatario</td>
                <td>N Doc</td>
                <td>Telefono</td>
                <td>Contenido</td>
                <td>Peso KG</td>
                <td>Peso VOL</td>
                <td>M3</td>
                <td>FT3</td>
                <td>VFOB</td>
                <td>Seguro</td>
            </tr>
        </thead>
        <tbody>
            @foreach ($manifiesto->guias as $guia)
                <tr>
                    <td>{{ $guia->guia->oficina->codigo }}-{{ $guia->idGuia }}</td>
                    <td>
                        @if ($guia->guia->entregaPP == 1)
                            Entrega Puerta a Puerta
                        @else
                            ZOOM
                        @endif
                    </td>
                    <td>
                        @if ($guia->guia->entregaPP == 1)
                            {{ $guia->guia->destinatario->direccion }}
                        @else
                            {{ $guia->guia->oficinaCourier->direccion }}
                        @endif
                    </td>
                    <td>{{ $guia->guia->cliente->nombres }} {{ $guia->guia->cliente->apellidos }}</td>
                    <td>{{ $guia->guia->destinatario->nombres }} {{ $guia->guia->destinatario->apellidos }}</td>
                    <td>{{ $guia->guia->destinatario->documento }}</td>
                    <td>{{ $guia->guia->destinatario->telefono }}</td>
                    <td>
                        @foreach ($guia->guia->articulos as $articulo)
                            ({{ $articulo->cantidad }}) {{ $articulo->producto }} <br>
                        @endforeach
                    </td>
                    <td>{{ $guia->guia->peso }}</td>
                    <td>{{ $guia->guia->peso_volumetrico }}</td>
                    <td>{{ $guia->guia->m3 }}</td>
                    <td>{{ $guia->guia->ft3 }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>

resources/views/pdfs/tickect.blade.php
<style>
    /** Define the margins of your page **/
    @page {
        margin: 10 0 0 0;
    }

    header {
        position: fixed;
        top: -110px;
        left: 0px;
        right: 0px;
        height: 50px;

        color: white;
        text-align: center;
        line-height: 35px;
    }

    .titulos {
        width: 100%;
        background-color: #b9b9b9;
        font-weight: 600;
        text-align: center
    }

    .contenidos {
        width: 90%;
        margin-left: 5%;
        font-size: 10;
        text-align: left
    }

    .contenidosTerminos {
        width: 90%;
        margin-left: 5%;
        font-size: 8;
        text-align: justify
    }

    .contenidosTotal {
        width: 90%;
        margin-left: 5%;
        font-size: 19;
        text-align: center;
        font-weight: 700
    }

    .contenidosTotal {
        width: 90%;
        margin-left: 5%;
        font-size: 13;
        text-align: center;
        font-weight: 700
    }

    .text-uppercase{
        text-transform: uppercase
    }
</style>
</head>

<body>
    <main style="text-align: center">
        <h3 class="text-uppercase">{{ $empresa->nombre }}</h3>
        ({{ $guia->oficina->codigo }}) - {{ $guia->oficina->nombre }} <br>
        Telefono: {{ $guia->oficina->telefono }} <br>
        {{ $guia->oficina->horario_atencion }} <br>
        {{ $guia->oficina->direccion }} <br>

        <table style="width: 100%">
            <tr style="width: 100%">
                <td style="width: 50%; ">
                    <h3 style="padding-left: 1rem">Tracking:</h3>
                </td>
                <td style="width: 50%; text-align: right; padding-right: 1rem">
                    <h3>{{ $guia->oficina->codigo }}-{{ $guia->id }}</h3>
                </td>
            </tr>
            <tr style="width: 100%">
                <td style="width: 30%; ">
                    <span style="padding-left: 1rem">Fecha:</span>
                </td>
                <td style="width: 70%; text-align: right; padding-right: 1rem">
                    <span style="padding-left: 1rem">{{ $guia->created_at }}</span>
                </td>
            </tr>
        </table>
        <br>
        <div class="titulos">
            REMITENTE
        </div>

        <div class="contenidos">
            <b>Nombre: {{ $guia->cliente->nombres }} {{ $guia->cliente->apellidos }}</b> <br>
            <b>Nro. Documento:  {{ $guia->cliente->documento }}</b> <br>
            <b>Telefono: {{ $guia->cliente->telefono }}</b> <br>
        </div>

        <br>
        <div class="titulos">
            DESTINTARIO
        </div>
        <div class="contenidos">
            <b>Nombre: {{ $guia->destinatario->nombres }} {{ $guia->destinatario->apellidos }}</b> <br>
            <b>Nro. Documento:  {{ $guia->destinatario->documento }}</b> <br>
            <b>Telefono: {{ $guia->destinatario->telefono }}</b> <br>
        </div>

        <br>
        @if($guia->entregaPP == 0)
        <div class="titulos">
            COURIER
        </div>
        <div class="contenidos">
            <tr style="width: 100%">
                <td style="width: 50%" class="">Pais Envio: <span class="text-uppercase">{{ $guia->paisOrigen }}
                    </span>
                </td>
                <td style="width: 50%">
                    <div class="text-right ">Pais Destino: <span class="text-uppercase">{{ $guia->paisDestino }}</span>
                    </div>
                </td>
            </tr>

            <b>Entrega:</b>  ZOOM<br>
            <b>Direccion:</b> {{ $guia->oficinaCourier->ciudad }} - {{ $guia->oficinaCourier->direccion }} <br>
        </div>
        @else
        <div class="titulos">
            ENTREGA PUERTA
        </div>
        <div class="contenidos">
            Pais Envio: <span class="text-uppercase">{{ $guia->paisOrigen }}
            </span>
            <div class="text-right ">Pais Destino: <span class="text-uppercase">{{ $guia->paisDestino }}</span>
            </div>
            <b>Direccion:</b> {{ $guia->destinatario->direccion }}  <br>
        </div>
        @endif

        <br>
        <div class="titulos">
            PAQUETE
        </div>
        <div class="contenidos">
            <b>Tipo Envio:</b> <span class="text-uppercase">{{ $guia->tipoGuia }}</span><br>
            <b>Peso KG:</b> {{ $guia->peso }} <br>
            <b>Peso Vol:</b> {{ $guia->peso_volumetrico }} <br>
            <b>Dimensiones:</b> {{ $guia->alto }}cm x {{ $guia->ancho }}cm x {{ $guia->largo }}cm <br>
        </div>

        @if($guia->montoSeguro != 0)
        <br>
        <div class="titulos">
            SEGURO ENVIO
        </div>
        <div class="contenidosTotal">
            {{ $guia->divisaSimbolo }} {{ $guia->montoSeguro }}
        </div>
        @else
        <br>
        <div class="titulos">
            SEGURO ENVIO
        </div>
        <div class="contenidosTotal2">
            ENVIO NO ASEGURADO
        </div>
        @endif

        <br>
        <div class="titulos">
            COSTO ENVIO
        </div>
        <div class="contenidosTotal">
            {{ $guia->divisaSimbolo }} {{ $guia->costo }}
        </div>

        <br>
        <div class="titulos">
            Terminos y Condiciones
        </div>

        <div class="contenidosTerminos">
            ENTIENDO Y ACEPTO QUE "{{ $empresa->nombre }}",
            NO ASUMIRÁ RESPONSABILIDAD ALGUNA POR LOS
            ENVIOS DECOMISADOS BIEN SEA POR CONTENER
            OBJETOS PROHIBIDOS O SOMETIDOS A DERECHO DE
            ADUANA O CONFISCADO POR LAS AUTORIDADES. Asi
            mismo declaro conocer que este servicio tiene limitaciones
            impuestos por razones de conveniencia general en defensa
            moral y pública de seguridad nacional, defensa del tesoro
            público y también por razones de interés del propio servicio y
            de sus funciones. De acuerdo con el principio anterior, certifico
            que no estoy enviando ningúno de los siguientes articulos. *
            Objetos cuya admisión o circulación esté prohibida en el país
            destino. * Dinero en efectivo y otros objetos de valor como
            (moneda, oro, platino, plata, piedras preciosas). * Materiales
            explosivos, informales, virus,agentes irritables o peligrosos. *
            Todo aquello que los convenios o acuerdos internacionales
            consagran como prohibida circulación. Dicho esto también
            declaro haber sido notificado que "Todos los envíos
            internacionales están sujetos a revisión por parte de las
            autoridades en los países de origen, destino y transito y pueden
            llegar a generar pagos de impuestos en el país de destino y/o
            demorarse por seguridad, por lo tanto, me comprometo a
            presentar y pagar ante las autoridades correspondientes los
            impuestos que pudiense generar en las aduanas nacionales o
            coordinar con el destinatario para el pago de los impuestos
            aduanales en el país destino en caso que así lo requieran las las
            autoridades correspondientes"
        </div>
    </main>
</body>

</html>